import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ShieldCheck, User, Mail, Phone, Check, RefreshCw } from 'lucide-react';
import { ScreenType } from '../../types';

interface AuthPageProps {
  setScreen: (screen: ScreenType) => void;
  onLoginSuccess: (user: any) => void;
}

export default function AuthPage({ setScreen, onLoginSuccess }: AuthPageProps) {
  // Authentication status view state: 'entry' (SSO Trigger) | 'profile' (Step 2 configuration for new accounts only)
  const [step, setStep] = useState<'entry' | 'profile'>('entry');
  const [activeMode, setActiveMode] = useState<'signin' | 'signup'>('signin');
  
  // Custom states for newly registering accounts
  const [name, setName] = useState('');
  const [phone, setPhone] = useState('');
  const [termsChecked, setTermsChecked] = useState(false);
  const [tempGoogleUser, setTempGoogleUser] = useState<any>(null);

  const [authError, setAuthError] = useState('');
  const [connecting, setConnecting] = useState(false);

  // Cached user profiles index
  const [profiles, setProfiles] = useState<any[]>(() => {
    const stored = localStorage.getItem('survivor_profiles');
    if (stored) {
      try {
        return JSON.parse(stored);
      } catch (e) {
        return [];
      }
    }
    return [
      {
        phone: "9128355670",
        name: "Nitesh Kumar",
        email: "niteshkumar9128ku@gmail.com",
        avatarUrl: ""
      }
    ];
  });

  // Listener to catch postMessage callbacks from Google OAuth popups
  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      // Validate origin is from standard run.app containers or localhost
      const origin = event.origin;
      if (!origin.endsWith('.run.app') && !origin.includes('localhost')) {
         // Allow dynamic subdomains or check standard structures
      }

      if (event.data?.type === 'OAUTH_AUTH_SUCCESS' && event.data?.user) {
        const googleUser = event.data.user;
        setConnecting(false);

        // Retrieve existing survivor ledger based on Gmail email
        const matchEmail = googleUser.email.trim().toLowerCase();
        const matchedProfile = profiles.find((p: any) => p.email && p.email.toLowerCase() === matchEmail);

        if (matchedProfile) {
          // Welcome back registered user instantly
          onLoginSuccess(matchedProfile);
        } else {
          // If Google profile already has a name, register and login instantly!
          if (googleUser.name && googleUser.name.trim()) {
            const completedProfile = {
              name: googleUser.name.trim(),
              email: googleUser.email.trim().toLowerCase(),
              phone: "Google Verified",
              avatarUrl: googleUser.avatarUrl || ""
            };
            
            // Save locally and complete login instantly!
            const updatedProfiles = [...profiles, completedProfile];
            setProfiles(updatedProfiles);
            localStorage.setItem('survivor_profiles', JSON.stringify(updatedProfiles));
            onLoginSuccess(completedProfile);
          } else {
            // Brand New User without a name: Transition to Step 2 to configure Name and preferences
            setTempGoogleUser(googleUser);
            setName(googleUser.name || '');
            setStep('profile');
          }
        }
      }
    };

    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
  }, [profiles, onLoginSuccess]);

  // Persist updated records
  const saveProfile = (profile: any) => {
    const updated = [...profiles, profile];
    setProfiles(updated);
    localStorage.setItem('survivor_profiles', JSON.stringify(updated));
  };

  // Google SSO Initiator
  const handleGoogleSignInByPopup = async () => {
    setAuthError('');
    setConnecting(true);

    try {
      const clientOrigin = window.location.origin;
      // Fetch dynamic authorization target URL generated by server
      const response = await fetch(`/api/auth/google/url?origin=${encodeURIComponent(clientOrigin)}`);
      if (!response.ok) {
        const errorText = await response.text().catch(() => "");
        throw new Error(`Auth Server Error (${response.status}): ${errorText || "Handshake connection timed out. Please execute again."}`);
      }

      const { url } = await response.json();

      // Open OAuth account chooser popup directly (handles sandboxed iframe restrictions cleanly)
      const popupWidth = 500;
      const popupHeight = 600;
      const leftCoord = window.screen.width / 2 - popupWidth / 2;
      const topCoord = window.screen.height / 2 - popupHeight / 2;

      const ssoPopup = window.open(
        url,
        'google_oauth_sso_portal',
        `width=${popupWidth},height=${popupHeight},top=${topCoord},left=${leftCoord},scrollbars=yes,status=no`
      );

      if (!ssoPopup) {
        setConnecting(false);
        setAuthError("Popup blocked by window. Please grant permissions above to connect Google SSO.");
      }
    } catch (err: any) {
      setConnecting(false);
      setAuthError(err.message || "Failed to establish bridge connection with Google authentication server.");
    }
  };

  // Profile setup handler (Step 2, asked after successful SSO validation)
  const handleSignUpComplete = (e: React.FormEvent) => {
    e.preventDefault();
    setAuthError('');

    if (!name.trim()) {
      setAuthError("Please disclose your survivor registration name.");
      return;
    }

    if (!termsChecked) {
      setAuthError("Please agree to the ledger registry terms.");
      return;
    }

    const completedProfile = {
      name: name.trim(),
      email: tempGoogleUser?.email || "new.survivor@gmail.com",
      phone: phone.trim() || "Guest Handset",
      avatarUrl: tempGoogleUser?.avatarUrl || ""
    };

    // Index coordinates locally
    saveProfile(completedProfile);
    onLoginSuccess(completedProfile);
  };

  return (
    <div className="min-h-screen bg-[#0D0D0D] text-white py-14 px-4 sm:px-6 lg:px-8 flex items-center justify-center">
      <div className="w-full max-w-md bg-[#141414] border border-amber-500/10 rounded-3xl p-6 sm:p-10 shadow-2xl space-y-6 relative overflow-hidden">
        
        {/* Decorative Watermark bg */}
        <div className="absolute top-0 right-0 p-6 select-none opacity-5 text-8xl">🪳</div>

        <AnimatePresence mode="wait">
          {step === 'entry' && (
            /* --- STEP 1: GOOGLE HANDSHAKE PORTAL --- */
            <motion.div
              key="sso-portal"
              initial={{ opacity: 0, scale: 0.98 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.98 }}
              className="space-y-6"
            >
              {/* Dual-Tab Navigation State selectors */}
              <div className="flex border-b border-neutral-900 text-xs font-mono">
                <button
                  type="button"
                  onClick={() => setActiveMode('signin')}
                  className={`flex-1 text-center pb-3 uppercase tracking-widest font-black transition-all border-b-2 cursor-pointer ${
                    activeMode === 'signin'
                      ? 'border-amber-500 text-amber-400'
                      : 'border-transparent text-zinc-500 hover:text-zinc-300'
                  }`}
                >
                  Sign In
                </button>
                <button
                  type="button"
                  onClick={() => setActiveMode('signup')}
                  className={`flex-1 text-center pb-3 uppercase tracking-widest font-black transition-all border-b-2 cursor-pointer ${
                    activeMode === 'signup'
                      ? 'border-amber-500 text-amber-400'
                      : 'border-transparent text-zinc-500 hover:text-zinc-300'
                  }`}
                >
                  Sign Up
                </button>
              </div>

              <div className="text-center space-y-1.5 pb-2">
                <h2 className="text-sm font-mono tracking-widest text-amber-500 uppercase font-black">
                  {activeMode === 'signin' ? 'CockroachKart Login' : 'Create Google SSO Account'}
                </h2>
                <p className="text-[11px] text-zinc-400 leading-relaxed font-mono">
                  {activeMode === 'signin' 
                    ? 'Log back into your registered profile instantly.'
                    : 'Any new user can register immediately using their Google Workspace profile.'}
                </p>
              </div>

              {/* Informative credentials status panel */}
              <div className="bg-[#1C1D20] border border-neutral-800 rounded-xl p-4 text-[11px] font-mono text-gray-400 space-y-1">
                <span className="text-amber-500 font-bold uppercase block text-[10px] tracking-wide mb-1">
                  🛡️ Secure Google Identity Integration
                </span>
                <p className="leading-relaxed">
                  Your transactions, loyalty points, and survival shipping coordinates map automatically to your verified Google profile.
                </p>
              </div>

              {authError && (
                <div className="text-[10px] bg-rose-500/10 border border-rose-500/20 text-rose-400 font-mono rounded-lg p-3 text-center leading-relaxed">
                  ⚠️ {authError}
                </div>
              )}

              <div className="space-y-3">
                <button
                  type="button"
                  disabled={connecting}
                  onClick={handleGoogleSignInByPopup}
                  className="w-full flex items-center justify-center gap-3 border border-neutral-800 bg-[#1E1E20] hover:bg-[#252528] rounded-xl py-3.5 text-xs font-mono font-black text-white hover:border-amber-500/40 transition-all cursor-pointer disabled:opacity-50 active:scale-[0.99] shadow-lg hover:shadow-amber-500/5 uppercase tracking-widest"
                >
                  {connecting ? (
                    <>
                      <RefreshCw className="h-4 w-4 animate-spin text-amber-500" />
                      Connecting with Google...
                    </>
                  ) : (
                    <>
                      <svg className="h-4.5 w-4.5 shrink-0" viewBox="0 0 24 24" fill="none">
                        <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"/>
                        <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/>
                        <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.06H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.94l3.66-2.85z" fill="#FBBC05"/>
                        <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.06l3.66 2.85c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/>
                      </svg>
                      {activeMode === 'signin' ? 'Sign In with Google' : 'Sign Up with Google'}
                    </>
                  )}
                </button>
              </div>

              <div className="flex flex-col gap-2 text-[10px] text-zinc-500 text-center font-mono pt-1">
                <p>Clicking above launches standard Google OAuth 2.0 account selectors in a secure popup sheet.</p>
                {activeMode === 'signin' ? (
                  <p>
                    New here?{' '}
                    <button
                      type="button"
                      onClick={() => setActiveMode('signup')}
                      className="text-amber-500 hover:text-amber-400 underline cursor-pointer font-bold uppercase tracking-wider"
                    >
                      Create Account
                    </button>
                  </p>
                ) : (
                  <p>
                    Already registered?{' '}
                    <button
                      type="button"
                      onClick={() => setActiveMode('signin')}
                      className="text-amber-500 hover:text-amber-400 underline cursor-pointer font-bold uppercase tracking-wider"
                    >
                      Sign In Instantly
                    </button>
                  </p>
                )}
              </div>
            </motion.div>
          )}

          {step === 'profile' && (
            /* --- STEP 2: FINISH PROFILE REGISTRATION (NEW USERS) --- */
            <motion.form
              key="profile-setup"
              initial={{ opacity: 0, x: 15 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -15 }}
              onSubmit={handleSignUpComplete}
              className="space-y-4 font-sans text-left"
            >
              <div className="text-center space-y-1 pb-2 border-b border-neutral-900">
                <span className="text-3xl select-none">🌱</span>
                <h2 className="text-sm font-mono tracking-widest text-amber-500 uppercase font-black">
                  Step 2: Profile Register
                </h2>
                <p className="text-[11px] text-zinc-400 leading-relaxed font-mono">
                  Verification successful! Setup your survivor parameters below.
                </p>
              </div>

              {/* Full name coordinate */}
              <div>
                <label className="block text-[10px] font-mono text-zinc-500 uppercase font-bold mb-1.5">
                  Survivor Full Name
                </label>
                <div className="relative">
                  <input
                    type="text"
                    required
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    placeholder="e.g. Nitesh Kumar"
                    className="w-full rounded-lg bg-[#1C1C1E] border border-neutral-800 pl-10 pr-3 py-2.5 text-xs text-white focus:border-amber-400 focus:outline-none focus:ring-1 focus:ring-amber-500 font-mono"
                  />
                  <User className="absolute left-3 top-3 h-4 w-4 text-neutral-600" />
                </div>
              </div>

              {/* optional Handset number */}
              <div>
                <label className="block text-[10px] font-mono text-zinc-500 uppercase font-bold mb-1.5">
                  Handset Phone Number (Optional)
                </label>
                <div className="relative">
                  <input
                    type="tel"
                    value={phone}
                    onChange={(e) => setPhone(e.target.value.replace(/\D/g, ''))}
                    placeholder="e.g. 91283XXXXX"
                    className="w-full rounded-lg bg-[#1C1C1E] border border-neutral-800 pl-10 pr-3 py-2.5 text-xs text-white focus:border-amber-400 focus:outline-none focus:ring-1 focus:ring-amber-500 font-mono tracking-wider"
                  />
                  <Phone className="absolute left-3 top-3 h-4 w-4 text-neutral-600" />
                </div>
              </div>

              {/* Verified details view */}
              <div className="bg-[#1C1D20] border border-neutral-800 rounded-lg p-3 space-y-2 text-[10px] font-mono">
                <div className="flex justify-between items-center">
                  <span className="text-zinc-500 uppercase text-[9px]">Verified Google SSO Email:</span>
                  <span className="text-white break-all text-right max-w-[180px] font-bold">{tempGoogleUser?.email || ''}</span>
                </div>
              </div>

              {authError && (
                <div className="text-[10px] font-mono text-rose-400 bg-rose-500/10 border border-rose-500/20 rounded-lg p-2.5 text-center leading-relaxed">
                  ⚠️ {authError}
                </div>
              )}

              <label className="flex items-start gap-2.5 text-[10px] text-zinc-500 cursor-pointer select-none py-1.5 hover:text-zinc-400 font-mono">
                <input
                  type="checkbox"
                  required
                  checked={termsChecked}
                  onChange={() => setTermsChecked(!termsChecked)}
                  className="accent-amber-500 rounded h-3.5 w-3.5 cursor-pointer mt-0.5"
                />
                <span className="leading-snug">
                  Agree to the terms of <strong className="text-amber-400">CJP Campaign Protocol</strong>. Verification maps your transactions securely to your devices.
                </span>
              </label>

              <button
                type="submit"
                className="w-full mt-2 cursor-pointer rounded-xl bg-amber-500 hover:bg-amber-600 transition-all py-3.5 text-xs font-mono uppercase font-black text-black tracking-widest shadow-lg shadow-amber-500/10 flex items-center justify-center gap-1.5 active:scale-[0.99]"
              >
                <Check className="h-4 w-4 stroke-[3]" />
                CREATE SHIELD ACCOUNT
              </button>
            </motion.form>
          )}
        </AnimatePresence>

        {/* SECURE DEPLOYMENT FOOTER */}
        <div className="border-t border-neutral-900 text-[10px] text-zinc-500 text-center font-mono flex items-center justify-center gap-1.5 pt-4">
          <ShieldCheck className="h-4 w-4 text-amber-500 shrink-0" />
          SSL AES-256 Google authentication handshake active
        </div>

      </div>
    </div>
  );
}
